# do not touch this line
configVersion: 2

description: recognition demo
keywords: cv
name: recog
displayName: Recog

events:
  - train
  
services:
  re:
    engine: recognition
    type: face

screens: 
  - train
  - recognize
  
widgets:
  train:
    event: train
    control: button
    label: 'Train your Face'
    value: 'Train'
  recognize:
    event: recog
    control: button
    label: Recognize Your Face
    value: Recognize
  
  