FROM node:8

MAINTAINER Sean Canton <sean.canton@admobilize.com>

RUN apt-get update && apt-get install -yq libzmq3-dev \
  && apt-get clean && rm -rf /var/tmp/*

COPY . /matrix
WORKDIR matrix/

RUN npm install -g nodemon
RUN rm -rf node_modules
RUN npm install
CMD ["node", "index.js"]
