FROM node:8

MAINTAINER Sean Canton <sean.canton@admobilize.com>

RUN apt-get update && apt-get install -yq libzmq3-dev \
  && apt-get clean && rm -rf /var/tmp/*

EXPOSE 8000

COPY ./bin/siege-server.js /index.js
COPY ./bin/creds /creds

CMD ["node","index.js"]
