#!/bin/bash -e

MATRIX_OS_LIB_PATH=/usr/lib/matrix-os
MATRIX_OS_STORE_PATH=/var/matrix-os
MATRIX_USER=matrixio-os

rm -rf $MATRIX_OS_LIB_PATH
rm -rf $MATRIX_OS_STORE_PATH
rm /lib/systemd/system/matrix-os.service

userdel -r $MATRIX_USER
